sudo: required

language: none

services:
  - docker

install: true

script:
  - docker build -t webapi .

deploy:
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker tag webapi zubant/webapi
    - docker push zubant/webap
